### ISSUE TITLE
Instant::now is not panic-free

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/easytime#6]
[The current `easytime::Instant::now` is just wrapping `std::time::Instant::now` with `Some`.](https://github.com/taiki-e/easytime/blob/master/src/instant.rs#L33-L35)

The implementation of `std::time::Instant::now` varies depending on the platform, but in any case it may cause a panic:

* https://github.com/rust-lang/rust/blob/master/src/libstd/time.rs#L157-L181
* https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/time.rs#L360
* https://github.com/rust-lang/rust/blob/master/src/libstd/sys/wasm/mod.rs#L298
* https://github.com/rust-lang/rust/blob/master/src/libstd/sys/redox/time.rs#L207
* https://github.com/rust-lang/rust/blob/master/src/libstd/sys/windows/time.rs#L227

I think the current easytime not become panic due to "untrusted input", but `std::time::Instant::now`'s panic is not related to "untrusted input".

**Comment by taiki-e** [comment]
Should it use std::panic::catch_unwind? https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5145c3cb33722bf7b97a42d4b6970273

**Comment by taiki-e** [comment]
cc @dtolnay

**Comment by dtolnay** [comment]
I looked only at unix since that's the one I know about.

It looks like the standard library implementation calls libc::clock_gettime with clk_id=CLOCK_MONOTONIC and tp a valid &mut timespec, and panics if clock_gettime returns -1.

According to https://linux.die.net/man/3/clock_gettime, the legal error cases for the clock_gettime family of functions are:

> - **EFAULT** — tp points outside the accessible address space.

Cannot happen because tp is right there on the stack.

> - **EPERM** — clock_settime() does not have permission to set the clock indicated.

Cannot happen because we are not calling clock_settime.

> - **EINVAL** — The clk_id specified is not supported on this system.

I suppose there can be systems that don't support CLOCK_MONOTONIC but it would be pretty unusual. Anyone developing for those systems would know about it and not be using Instant, or using Instant only after checking what clocks exist.

So I would say that for unix I would not consider it necessary to call Instant::new inside catch_unwind.

If someone later specifically requests for better support for systems without a monotonic clock, I would want to understand more about their use case before making a code change. It is likely that they would be better served by a separate function like:

```rust
fn has_monotonic_clock() -> bool {
    panic::catch_unwind(Instant::new).is_ok()
}
```

**Comment by taiki-e** [comment]
Thanks for looking!

> Anyone developing for those systems would know about it and not be using Instant, or using Instant only after checking what clocks exist.

Indeed!

> If someone later specifically requests for better support for systems without a monotonic clock, I would want to understand more about their use case before making a code change.

I strongly favor this.

I also looked at other platforms, and I think that it is not necessary to use catch_unwind, so I close this issue.

* windows - `QueryPerformanceCounter` https://msdn.microsoft.com/en-US/library/windows/desktop/ms644904
  > On systems that run Windows XP or later, the function will always succeed and will thus never return zero.

  I think that it is unnecessary to support os which supports ended more than five years ago.

* unix (except macos and ios) - `libc::clock_gettime` https://github.com/taiki-e/easytime/issues/6#issuecomment-468868452

* macos and ios - `libc::mach_absolute_time` 
There was no description in the [official document](https://developer.apple.com/documentation/kernel/1462446-mach_absolute_time?language=occ), but [this function does not return an error](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/time.rs#L141) in the first place.

* redox - `syscall::clock_gettime` https://github.com/redox-os/kernel/blob/master/src/syscall/time.rs#L7-L17
  [`std::time::Instant::now` passes `syscall::CLOCK_MONOTONIC`](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/redox/time.rs#L129), so it is not fail.

* wasm - https://internals.rust-lang.org/t/what-is-the-plan-regarding-libstd-and-wasm-syscalls/8497
  Unless the unstable `wasm_syscall` feature is enabled, it will always be panic, but stabilization of `wasm_syscall` feature is not planned, and external crate seems to provide these features, so I think that there is no problem.
